User can view a list of courses (Main screen)
nilenso/dhobi-seva-electron pull request #10
Opened 2017-02-27 11:13 UTC by mukeshm

PR for issue #2

2017-03-01 14:56 UTC, deobald requested changes
Looks good, @mukeshm ! Just a couple changes and you can merge.

2017-03-01 14:56 UTC, deobald commented on src/components/CreateCourse.js
>    isNameValid(name){
Try to keep validation in its own namespace/module/class/etc, regardless of language.

2017-03-01 14:56 UTC, deobald commented on src/components/CreateCourse.js
>    console.log('event,arg', arg)
log output might be confusing (mentions `event,arg` but only displays `arg`)

I'm not familiar enough with JS -- is it common to do `console.log` in lieu of a real logging framework? This stuff would be much easier to debug/trace if it were written to file.

2017-03-01 14:56 UTC, deobald commented on src/components/ViewCourses.js
> +                  let date = new Date(course.startDate)
Is there a way to pull this variable out of the JSX? Preferably, all templating would just be HTML and tokens.

2017-03-01 14:56 UTC, deobald commented on src/components/ViewCourses.js
> +        {this.state.courseList ? this.renderData() : this.renderLoading()}
Same as comment above: Can you pull this logic out of the JSX?

A good thumb rule to keep in mind is: StringTemplate (one of the original templating libs for HTML templating) at one point did not even *contain* a conditional statement, so testing booleans like this was actually impossible to do in the view. This was the right choice on the part of the StringTemplate designers and can still be followed today.

2017-03-01 14:56 UTC, deobald commented on src/css/style.css
> +        cursor: pointer;
Tabs, spaces, x2, x4, x8 ...doesn't matter but remember to keep it consistent across the entire project (and definitely within one file).

I won't comment on the quality of the CSS, sorry... takes too long to read and understand to the level where I can say something meaningful. 😛

2017-03-03 13:03 UTC, rishabh09 commented on src/components/CreateCourse.js
>    console.log('event,arg', arg)
Removed the console.log, it was just for development.

2017-03-03 13:08 UTC, rishabh09 commented on src/components/ViewCourses.js
> +                  let date = new Date(course.startDate)
Created a new method for map function inside component class, can't pull `date` variable outside  the JSX. It is there just to parse start date ISO string into date object

2017-03-05 10:21 UTC, rishabh09 commented on src/components/ViewCourses.js
> +        {this.state.courseList ? this.renderData() : this.renderLoading()}
moved this conditional statement from render to separate `getData` function.

2017-03-08 05:02 UTC, mukeshm commented on src/components/CreateCourse.js
>    console.log('event,arg', arg)
Will add system-wide logger in #11

2017-03-08 05:29 UTC, mukeshm commented on src/components/CreateCourse.js
>    isNameValid(name){
Validation is now in a separate module.

2017-03-08 05:32 UTC, merged