User can start a course
nilenso/dhobi-seva-electron pull request #9
Opened 2017-02-22 12:27 UTC by mukeshm

PR for issue #8

2017-02-23 14:09 UTC, deobald requested changes
Nice job! I only had one comment to make.

2017-02-23 14:09 UTC, deobald commented on src/components/CreateCourse.js
> +    }else {
The above code is pretty repetitive and a lot of nested ifs. How do you think you could make it cleaner? :)

2017-02-23 14:13 UTC, rishabh09 commented on src/components/CreateCourse.js
> +    }else {
ok, will try to make it cleaner.

2017-02-24 05:51 UTC, rishabh09 commented on src/components/CreateCourse.js
> +    }else {
@deobald All the nested ifs and repetitive code are removed.

2017-02-24 06:31 UTC, merged

2017-03-02 11:50 UTC, deobald reviewed
wups! I forgot to submit the review. sorry.